source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.3.1'

gem 'rails', '~> 5.2.0.rc1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'webpacker'

gem 'bootsnap', '>= 1.1.0', require: false

gem 'devise'
gem 'bootstrap'
gem 'kaminari'
gem 'simple_form'
gem 'responders'
gem 'react-rails'
gem 'pundit'
gem 'mini_form'
gem 'graphql'
gem 'search_object'
gem 'search_object_graphql'
gem 'graphql-pundit'
gem 'graphql-batch'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 3.7'
  gem "factory_bot_rails", "~> 4.0"
  gem 'pry'
end

group :development do
  gem 'graphiql-rails'
  gem 'annotate'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara', '~> 2.15'
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'chromedriver-helper'
end


